### ISSUE TITLE
请问下ui是使用什么绘制的？我使用Cambalache 和glade都打不开，打开报错

### ISSUE THREAD

**Issue by Booleis** [xuthus5/coco#2]
![QQ截图20220826074504](https://user-images.githubusercontent.com/38277075/186802586-5ad9a7ed-d7f0-4895-b43a-903e62f7554f.png)
![QQ截图20220826074528](https://user-images.githubusercontent.com/38277075/186802600-0ebbdf68-77ed-471d-a4af-01ccf4db06d8.png)
![QQ截图20220826074542](https://user-images.githubusercontent.com/38277075/186802610-8c0d7a14-6045-475c-beb8-3d16c2b354cf.png)
以下是截图

**Comment by xuthus5** [comment]
你好，使用的GTK4+libadwaita。目前 Cambalache 和 glade 对GTK4的部分语法不兼容。
